[package]
name = "simple_weather_astrobox_v2_plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.60.0", features = ["inter-task-wakeup"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22"
png = "0.17"
jpeg-decoder = "0.3"
image-webp = { version = "0.2", default-features = false }
zip = { version = "3.0", default-features = false, features = ["deflate"] }
waki = "0.3"
url = "2"
flate2 = "1"
